### ISSUE TITLE
Specify project-level default version for targets

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#106]
This would set the version for all targets specified by the project (not its subprojects).
The version could still be overridden target-wise, if needed.
E.g.,

```toml
[[subproject]]
    name = "boost"
    version = "boost-1.65.0"

[subproject.filesystem]
    target_type = "static library"
    url = "https://github.com/boostorg/filesystem"

[subproject.system]
    target_type = "static library"
    url = "https://github.com/boostorg/system"
    version = "boost-1.66.0"

# ...
```
