### ISSUE TITLE
Add project- and target-properties to deactivate default flags

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#131]
While our defaults are opinionated, we cannot claim that our flags are _always_ the right choice. Therefore, I would like to add a switch on both project- and target-level to deactivate them:
```toml
[myexe]
  default_compile_flags = false
  default_link_flags = false
```

The feature is already implemented in `BuildFlags`, it just needs to be exposed.
