### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#15]
In the readme it says

```toml
# Include an external package/target (i.e. not from this toml file)
[somelib]
external = true
path = "/path/to/sources"

# Build an executable and link the library
[myexe]
[myexe.sources]
include_directories = ["include", "mylib.sources.include_directories"]
source_directories = ["src"]

[myexe.link]
dependencies = ["somelib"]
```

Shouldn't it read: `somelib.sources.include_directories`?

Also I am not sure I understand the example. So we have the linker dependency on `somelib`. Why do we have to explicitly give it the source files again? This seems redundant and error prone (one might forget one or the other and not directly notice it, because there is an entry already that states that there is a dependency).
