### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#26]
On PR #23, a lot of changes were made and the documentation needs to be updated accordingly.

- [x] update Readme with better example of small config file and a full config file
- [x] update Readme and make it more compact
- [x] add docs folder and readthedocs
- [x] add step by step incremental guide to documentation in docs folder
- [x] add note that boost filesystem can be built with this, as a non-trivial example of a real-world application

**Comment by GPMueller** [comment]
Maybe something like this?
```toml
[mytarget]
output_name = "myexe"      # will get pre- and suffix according to system
target_type = "executable" # or "shared library", "static library", "header only"

# target sources can be downloaded
external = true # default:false
url = "https://github.com/trick-17/mylib"
version = 1.1 # will try to git checkout [v]1.1[.*]

# source directory is taken relative to the configuration file,
# or relative to the download directory if the target is external
directory = "relativedir"

# other targets that mytarget should be linked to
dependencies = ["myothertarget"]

# finer control over where source files are and what should be in-/excluded
[mytarget.sources]
file_extensions = [".hpp", ".cpp"]
include_directories = ["include"]
source_directories  = ["src"]

# should this really exist?
[hello.properties]
cpp_version = 17
```
