### ISSUE TITLE
Allow sub-projects (modularisation)

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#36]
This is very important for modularisation and usage of external projects.
Currently, only targets are allowed to be included from external.

The difference with an external project should be that the corresponding directory (irrespective of being downloaded or a (sub)directory) should be searched for a project file, and tried with a default configuration if none is found (the latter would be equivalent to an empty external target).

The project syntax could for example be
```toml
[project: myproject]
[myexe]
output_name  = "run"
dependencies = ["somelibrary", "otherlibrary"]

[project: someproject]
# the project file of this project should define the targets "somelibrary" and "otherlibrary"
external    = true
url         = "https://github.com/someteam/someproject"
```

While the target-based version would download the same project twice:
```toml
[myexe]
output_name  = "run"
dependencies = ["Eigen"]

[somelibrary]
target_type = "shared library"
external    = true
url         = "https://github.com/someteam/someproject"
directory = "somelibrary"

[otherlibrary]
target_type = "shared library"
external    = true
url         = "https://github.com/someteam/someproject"
directory = "otherlibrary"
```

**Comment by NOhs** [comment]
Why do we need the additional complexity with the projects? Can't we just have external projects import more than one target? Also I think your toml file is invalid toml syntax. The space after `project:` is not allowed without quotation marks.

**Comment by GPMueller** [comment]
> Why do we need the additional complexity with the projects?
Are you asking why we should add "project" as a further layer of abstraction or which *complexity* do you mean?

> Can't we just have external projects import more than one target?
That's the idea here. Since an external *target* is by definition only a single target, there should also be some way to incorporate entire projects with more than one target.

**Comment by GPMueller** [comment]
When creating a project with multiple targets, one should specify the project name:
```toml
[project:someproject]
[someexe]
output_name  = "run"
[somelib]
```

Then, another project may include this:
```toml
[project:myproject]
[myexe]
dependencies = ["someproject.somelibrary", "someproject.otherlibrary"]

[project]
# the project file of this project should define the targets "somelibrary" and "otherlibrary"
url         = "https://github.com/someteam/someproject"
```

If no project name is specified, the corresponding toml file can only be used as external project file, if a name is specified in the "consuming" project (this will also override any name specified in that project), e.g.
```toml
[project:someproject]
url         = "https://github.com/someteam/someproject"
```
