### ISSUE TITLE
Do we always need output_name?

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#51]
I am currently writing the user guide and I noticed that while it is nice to have a simple name for the target and maybe are more complex name for the output file, by default it would be nice if the target name would be taken over if no output_name is given.

```toml
[myexe]
```
should produce `myexe.exe` on Windows while

```toml
[myexe]
output_name = "MyApp-v1.0-test1234"
```

should of course behave like before.
