### ISSUE TITLE
Target-name and folder name

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#52]
Did we already decide on whether we want to identify folders from target names? E.g.:

    my_project
    ├── shared_headers
    |   └── header1.hpp
    ├── my_executable
    |   ├── include
    |   |   ├── header1.hpp
    |   |   └── header2.hpp
    |   └── src
    |       ├── src1.cpp
    |       └── src2.hpp
    ├── my_lib
    |   ├── include
    |   |   └── header3.hpp
    |   └── src
    |       └── src3.hpp
    └── clang-build.toml

```toml
[shared_headers] # Do we even need this?

[my_lib]
target_type = "shared library"
output_name  = "the_lib"

[my_executable]
dependencies = ["my_lib", "shared_headers"]
```
