### ISSUE TITLE
Automatically discover and enable building of tests and examples

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#72]
**Questions which need to be answered in order to implement this:**
- how to set include directories and flags for tests and examples
- should one be able / how to switch between one test per source file and one executable for all the sources
- what should be the build folder structure
- can / should include directories and flags be set per example
- can / should we enable more complex examples, where additional sources are compiled into an example
- should there be a command build tests, e.g. `clang-build tests` and/or to run tests, e.g. `clang-build runtests`

**My suggestions for what we should encourage:**
- tests should be inside a `tests` folder and examples in an `examples` folder
- sources inside the tests folder should be compiled into a single executable
- sources in the examples folder should be compiled into one example each

**Example config:**
```toml
[mylib]
    target_type = "static library"
    sources = ["src/*.cpp"]

[mylib.tests]
    sources = ["tests/*.cpp"]

[mylib.examples]
    include_directories = ["deps"]
    sources = ["examples/*.cpp", "deps/something.cpp"] # does something like this make sense?
    [mylib.examples.flags]
        compile = ["-Wno-unused-parameter"]
```
